### ISSUE TITLE
New API version

### ISSUE THREAD

**Issue by potatoqualitee** [mkht/PSOpenAI#10]
Don't know if you saw but there's awesome new features that were just released!

https://platform.openai.com/docs/assistants/whats-new

There's a vector store which I think will be very helpful for my use-cases.

**Comment by mkht** [comment]
Yeah, yeah, of course I know that.

I am currently working on the implementation of the Batch API and expect to release it in the next few days. After that I will work on Assistants v2.

But I'm busy with my job right now, so it may take some time.

**Comment by mkht** [comment]
Vector Store and Assistants v2 implemented in v3.8.0

**Comment by potatoqualitee** [comment]
omg yessssssss!

**Comment by potatoqualitee** [comment]
Your documentation is so fantastic. Love the guides! I'll be promoting your module at PSConf.eu as it'll be part of my PSU/ChatGPT presentation.
