### ISSUE TITLE
Azure files

### ISSUE THREAD

**Issue by potatoqualitee** [mkht/PSOpenAI#20]
I was using PSOpenAI in my PSHelp.Copilot module and noticed the Azure commands did not have help.

I also noticed that it is not called by any of your documentation.

I was lost as an end-user, thinking I had to care about them. Mind if I submit a PR with the Azure commands moved to Private and removed from the PSD1? These seem like purely internal commands.

**Comment by mkht** [comment]
Are you talking about commands that are prefixed with Azure, such as Request-AzureChatCompletion?

We are leaving those for backward compatibility. We intend to remove them in the next major version. Probably in July.

This is also noted in the README.

**Comment by potatoqualitee** [comment]
yes, those are the ones. cool, sounds good!
