### ISSUE TITLE
Structured outputs

### ISSUE THREAD

**Issue by potatoqualitee** [mkht/PSOpenAI#29]
OpenAI introduced this incredibly helpful requirement for output.

https://openai.com/index/introducing-structured-outputs-in-the-api/

**Comment by mkht** [comment]
Of course I will add this parameter. I will be able to work on it next weekend.

**Comment by mkht** [comment]
Structured Outputs now supported in release [v4.1.0](https://github.com/mkht/PSOpenAI/releases/tag/v4.1.0)

Please refer to this guide for usage.
[Guide: How to use Structured Outputs](https://github.com/mkht/PSOpenAI/blob/main/Guides/How_to_use_StructuredOutputs.md)
