### ISSUE TITLE
PSOpenAI-mini

### ISSUE THREAD

**Issue by potatoqualitee** [mkht/PSOpenAI#32]
Hello, considering local OpenAI API endpoints are getting popular, any chance for something like PSOpenAI for local APIs?

These apps run OpenAI APIs locally:

https://github.com/open-webui/open-webui
https://jani.ai

And also VS Code's AI Toolkit. 

![image](https://github.com/user-attachments/assets/d2564994-06a9-4976-b7e7-54df8dc0d0c7)

I wrote a module for that but it's specific to that implementation.

https://github.com/potatoqualitee/aitoolkit

btw, Irwin Strachan wanted me to pass this on:

> That PSOpenAI module is something! I thought I knew PowerShell... He/She is on another level! Oh and the examples, Straight gold! I love the fact he's using classes for structured data! That makes so much sense! Give the developer my regards! Willing to buy him a cup of coffee! :-)

Also I wrote about PSOpenAI here:

https://blog.netnerds.net/2024/08/structured-output-openai-chatgpt-ai-integration-powershell/

I used it to do this:

![image](https://github.com/user-attachments/assets/3366bba3-a973-4841-82cd-54df79775b54)

**Comment by mkht** [comment]
PSOpenAI can use an OpenAI compatible API server, just specify the local server address in the `$env:OPENAI_API_BASE` variable. I have tested this in LM Studio.

```powershell
# This script demonstrates how to use the PSOpenAI to interact with the OpenAI compatible API server
$env:OPENAI_API_BASE = 'http://localhost:1234/v1'
$env:OPENAI_API_KEY = 'dummy-key'

$modelName = 'lmstudio-community/Phi-3.1-mini-128k-instruct-GGUF/Phi-3.1-mini-128k-instruct-Q4_K_M.gguf'
$systemMessage = 'Always answer in rhymes. Today is Thursday'
$userMessage = 'What is the weather today?'

Request-ChatCompletion -Model $modelName -SystemMessage $systemMessage -Message $userMessage
```

Let me know if you have problems with other local API servers.

And thanks for introducing my module. By the way, I like tea.  (just kidding of course).

**Comment by potatoqualitee** [comment]
Oh, fantastic, thank you! I'll adjust my code. And let Irwin know your tea preference ;)
