### ISSUE TITLE
add -Proxy parameter

### ISSUE THREAD

**Issue by Davider-code** [mkht/PSOpenAI#4]
my System: windows 10 Pro 21H2, Powershell 5.1

I'm a novice in PowerShell. The network I'm using cannot directly access the ChatGPT API. I need to use a proxy for access. However, when using the following code, I don't receive any response.

```
$env:http_proxy = "http://127.0.0.1:1081"
$env:https_proxy = "http://127.0.0.1:1081"
$global:OPENAI_API_KEY = "sk-XXXXX"
$Result = Request-ChatCompletion -Message "Who are you?"
Write-Output $Result.Answer
```

Therefore, I hope to add a **-Proxy** parameter, just like below, so that I can successfully use the following code to install the module
```
Install-Module -Name PSOpenAI -Force -Proxy "http://127.0.0.1:1081"
```

**Comment by mkht** [comment]
Good suggestion, the OpenAI official Python SDK has this functionality.

I think it is not too difficult to implement. However, I am not using a proxy so I may have to set up a network to test it works.

There are already numerous parameters to Request-ChatCompletion, so I'm a bit concerned if it would be appropriate to add more -Proxy parameters. Perhaps it would be better to read it from an environment variable instead of a parameter.

**Comment by Davider-code** [comment]
I've previously used similar C# code to set up a proxy, for reference
```
		string url = $"https://translate.googleapis.com/translate_a/single?client=gtx&sl={sLang}&tl={tLang}&dt=t&q={Uri.EscapeDataString(input)}";

		HttpClientHandler handler = new HttpClientHandler
		{
			Proxy = new WebProxy("http://127.0.0.1:1081") // set Proxy 1081
		};

		using (HttpClient httpClient = new HttpClient(handler))
		{
			string result = httpClient.GetStringAsync(url).Result;
			dynamic jsonData = Newtonsoft.Json.JsonConvert.DeserializeObject(result);
			string translation = jsonData[0][0][0];
			return translation;
		}
```

**Comment by mkht** [comment]
After some research and testing, it appears that requests can be executed through a proxy by using PowerShell's built-in proxy support.

```PowerShell
# Windows PowerShell 5.1
$proxyAddress = 'http://127.0.0.1:8888/'
[System.Net.WebRequest]::DefaultWebProxy = [System.Net.WebProxy]::new($proxyAddress)
Request-ChatCompletion -Message 'Hello from behind proxy'
```
```PowerShell
# PowerShell 7
$proxyAddress = 'http://127.0.0.1:8888/'
[System.Net.Http.HttpClient]::DefaultProxy = [System.Net.WebProxy]::new($proxyAddress)
Request-ChatCompletion -Message 'Hello from behind proxy'
```

It seems to me that by using this solution, there is no need to add a `-Proxy` parameter to PSOpenAI. Would this satisfy your needs?

**Comment by Davider-code** [comment]
> After some research and testing, it appears that requests can be executed through a proxy by using PowerShell's built-in proxy support.
> 
> ```powershell
> # Windows PowerShell 5.1
> $proxyAddress = 'http://127.0.0.1:8888/'
> [System.Net.WebRequest]::DefaultWebProxy = [System.Net.WebProxy]::new($proxyAddress)
> Request-ChatCompletion -Message 'Hello from behind proxy'
> ```
> 
> ```powershell
> # PowerShell 7
> $proxyAddress = 'http://127.0.0.1:8888/'
> [System.Net.Http.HttpClient]::DefaultProxy = [System.Net.WebProxy]::new($proxyAddress)
> Request-ChatCompletion -Message 'Hello from behind proxy'
> ```
> 
> It seems to me that by using this solution, there is no need to add a `-Proxy` parameter to PSOpenAI. Would this satisfy your needs?

Thanks for your help. The code provided above works great. 
Your project is the most feature-rich one I have come across. Great job!
