### ISSUE TITLE
Azure vs Not Azure

### ISSUE THREAD

**Issue by potatoqualitee** [mkht/PSOpenAI#8]
My understanding of Azure vs Not Azure is that it's a small change in URL path and some extra variables.

Would you have any interest in collapsing the commands to detect if the person wants Azure, and if so, build the commands out that way? That could be done with detection of the different `$env:` values or using a ` Set-` command, along with a module-scoped `$script:` variable, perhaps with a hashtable value.

I ask because I'm interesting in adding finetuning support (with your blessing) and would prefer to make half the commands currently required. It seems like it'd be more enjoyable to navigate as an end-user as well.

**Comment by mkht** [comment]
In fact, most Azure versions of the function internally just call the OpenAI version using non-public parameters.
The two codes are technically identical.

```powershell
Request-AzureChatCompletion -Message 'Hello.' -Deployment 'gpt-35-turbo' `
    -ApiKey $AZURE_API_KEY `
    -ApiBase $AZURE_API_BASE

Request-ChatCompletion -Message 'Hello.' -Model 'gpt-35-turbo' `
    -ApiKey $AZURE_API_KEY `
    -ApiBase $AZURE_API_BASE `
    -ApiType Azure `
    -AuthType Azure
```

What we can do immediately is document and publish these non-public parameters.
Almost all functions can be switched to the Azure version by simply specifying `-ApiType` and `-AuthType` as `"Azure"`.

Your suggestion of "switch" by environment variables is not a bad idea, but I don't think it is used much in PowerShell.

As the variety of API endpoints increases, it is becoming more and more difficult to provide and maintain both Azure and OpenAI functions.
In the near future I will discontinue the Azure* functions and integrate it with the OpenAI version.
This would be a breaking change and I wll raise the major version.

Finally, the implementation of fine-tuning is on my to-do list. However, it is not a priority for me. Working on the recently added Batch API will come first.
If you are willing to contribute, I would welcome it.

**Comment by potatoqualitee** [comment]
> Your suggestion of "switch" by environment variables is not a bad idea, but I don't think it is used much in PowerShell.

`$env:` is used quite a bit in certain contexts, especially when it comes to secrets and Linux interoperability. Environmental variables are generally favored over `$global:`, though I use $global when it's required within embedded scriptblocks and ProgressPreference.

I avoided $env in Windows at first, instead opting for config files, but have since come to favor $env: I use _the hell_ out of module scoped variables though.

I wrote a finetuning module called finetuna, and plan to port my code style to your own and add many of the commands to your toolset to make it more complete.

https://github.com/potatoqualitee/finetuna

Wish I knew about this module before I did the embedddings. The embeddings commands I added were out of scope, but I had no better place to put them. I was  relieved to see it was included in your module.

**Comment by mkht** [comment]
My explanation was not good, sorry.

I understand that storing the secret in an environment variable is a common use case. In fact, PSOpenAI reads API key and API endpoint URL from environment variables.

My point was that using environment variables to switch behavior may not be in keeping with PowerShell common style.

For example, if `$env:USE_AZURE = $true`, then automatically setting the `-ApiType` to `Azure` would not be difficult to implement, but it would be confusing to the user. Instead, I feel that switching by function parameters is more straightforward and more in line with the function oriented PowerShell style.

```powershell
$env:OPENAI_API_KEY = 'api key for azure'
$env:OPENAI_API_BASE = 'https://your-endpoint-url'

# Should this call Azure or OpenAI?
$env:USE_AZURE = $true
Request-ChatCompletion -Model 'gpt-4' -Message 'Hello' -ApiType 'OpenAI'
```

If it is not convenient for you to specify parameters for Azure in your own scripts each time, you can use several techniques.

#### Tip1. Set custom default values for cmdlet parameters
```powershell
if ($env:USE_AZURE) {
    $PSDefaultParameterValues = @{
        'Request-ChatCompletion:ApiType'  = 'Azure'
        'Request-ChatCompletion:AuthType' = 'Azure'
        'Request-AudioSpeech:ApiType'     = 'Azure'
        'Request-AudioSpeech:AuthType'    = 'Azure'
    }
}
# These implicitly call Azure
Request-ChatCompletion -Model 'gpt-4' -Message 'Hello'
Request-AudioSpeech -Text 'How are you?' -Model 'tts-1-hd' -OutFile 'Voice.mp3'
```

#### Tps 2. Use splatting for common parameters
```powershell
if ($env:USE_AZURE) {
    $CommonParams= @{
        'ApiType'  = 'Azure'
        'AuthType' = 'Azure'
    }
}
else {
    $CommonParams= @{
        'ApiType'  = 'OpenAI'
    }
}

Request-ChatCompletion -Model 'gpt-4' -Message 'Hello' @CommonParams
Request-AudioSpeech -Text 'How are you?' -Model 'tts-1-hd' -OutFile 'Voice.mp3' @CommonParams
```

**Comment by potatoqualitee** [comment]
Ah, I understand now.

In this case, I was thinking that if an azure env with all the necessary vars was set, it'd choose that one unless a Set Provider command was used. Then again, it requires a hashtable which $env: does not support (or json, which is an extra step), so I didn't think that one through 😅 

I like your first solution, as well as Doug's:

```powershell
$secrets = @{
    apiURI         = "<Your Azure OpenAI API URI>"
    apiVersion     = "<Your Azure OpenAI API Version>"
    apiKey         = "<Your Azure OpenAI API Key>"
    deploymentName = "<Your Azure OpenAI Deployment Name>"
}

Set-OAIProvider AzureOpenAI
Set-AzOAISecrets @secrets
```

PSDefaultParameterValues are a favorite of mine, though Doug's approach to this specific issue feels more PowerShelly. I'd do a bit more magic, though. If they use the Set Azure Secrets command, it'd auto Set the Provider to Azure for them. And if they need to use regular OAI, then just set it back.

In dbatools, we have a whole library to do persistence and configs for us, though I've often thought a config.json files stored in the user's home path would be easier. That's what I used in my twitch client.

```powershell
switch ($PSVersionTable.Platform) {
    "Unix" { $script:configfile = "$home/tvclient/config.json" }
    default { $script:configfile = "$env:APPDATA\tvclient\config.json" }
}

if (-not (Test-Path -Path $script:configfile)) {
    $null = New-ConfigFile
}
```

I tend to avoid having common params and prefer to use module scoped $script: vars instead. Mostly because I don't want to maintain that many parameters, though I see how they are convenient for the end-user to easily switch back and forth.

**Comment by potatoqualitee** [comment]
Oh! Something else I do in my modules is that I use PSDefaultParameterValues within my psm1. That helps me control parameters later on, without me having to write it out each time like `[string]$API = $script:Apikey`

**Comment by mkht** [comment]
I am thinking of adding `Set-OpenAIContext` as a helper function to set the implicit context.

Please let me know what you think about this idea.

### 1. Parameters specified in a context are used implicitly.
```powershell
## Azure (with context)
$Contexts = @{
    ApiType    = 'Azure'
    ApiKey     = 'your-azure-api-token'
    ApiBase    = 'https://<endpoint>.openai.azure.com/'
    ApiVersion = '2024-03-01-preview'
    AuthType   = 'Azure'
}
Set-OpenAIContext @Contexts
Request-ChatCompletion -Message 'Hello Azure' -Model 'gpt-4'

## OpenAI (with context)
$Contexts = @{
    ApiType      = 'OpenAI'
    ApiKey       = 'your-openai-api-token'
    Organization = 'Contoso'
}
Set-OpenAIContext @Contexts
Request-ChatCompletion -Message 'Hello OpenAI' -Model 'gpt-4'
```

### 2.  Contexts take precedence over environment variables, but not over explicit parameters.
```powershell
$env:OPENAI_API_KEY = 'api-key-1'

# It uses "api-key-1" for API Key
Request-ChatCompletion -Message 'Hello OpenAI' -Model 'gpt-4'

$Contexts = @{
    ApiType      = 'OpenAI'
    ApiKey       = 'api-key-2'
}
Set-OpenAIContext @Contexts

# It uses "api-key-2"
Request-ChatCompletion -Message 'Hello OpenAI' -Model 'gpt-4'

# It uses "api-key-3"
Request-ChatCompletion -Message 'Hello OpenAI' -Model 'gpt-4' -ApiKey 'api-key-3'

# Explicit parameters always override context and environment variables
## Azure (explicit)
Request-ChatCompletion -Message 'Hello Azure' -Model 'gpt-4' -ApiType 'Azure' -ApiKey 'azure-api-token' -ApiBase 'https://<endpoint>.openai.azure.com/'
## OpenAI (explicit)
Request-ChatCompletion -Message 'Hello OpenAI' -Model 'gpt-4' -ApiType 'OpenAI' -ApiKey 'openai-api-token'
```

### 3. The context is initialized by `Clear-OpenAIContext`
```powershell
# Set context for Azure
$Contexts = @{
    ApiType    = 'Azure'
    AuthType   = 'Azure'
}
Set-OpenAIContext @Contexts

# Back to default 
Clear-OpenAIContext

## OpenAI (without context)
Request-ChatCompletion -Message 'Hello OpenAI' -Model 'gpt-4'
```

**Comment by potatoqualitee** [comment]
I love it, very nice and clean.

**Comment by potatoqualitee** [comment]
about to publish this!

https://github.com/potatoqualitee/dbatools.ai

it uses your module. i was about to update your module with the azure stuff so it could support azure too, but it seems like you're working on it now? saw a commit from 3 hours ago that suggested it 😊

**Comment by mkht** [comment]
Yes. I am working on this right now, but it is not finished yet. There are some edge cases that are not working and need to be fixed.

**Comment by mkht** [comment]
v3.13.0, that implements this, has been released.
https://github.com/mkht/PSOpenAI/releases/tag/v3.13.0

**Comment by potatoqualitee** [comment]
HeYYYYYYY!!!!! That was fast! So exciting, thank you!
